### ISSUE TITLE
Actor is same before & after the self mutation

### ISSUE THREAD

**Issue by mlajtos** [voltrevo/ValueScript#1] opened 2023-03-04 20:10 UTC
Hey @voltrevo, ValueScript is a pretty neat idea.

I read your post about [ValueScript’s Unique Strategy for Preventing Side Effects](https://itnext.io/valuescripts-unique-strategy-for-preventing-side-effects-ac8133735a11). From the description you provided, I would expect that first and second instance (or variable pointing to an object) of the `actor` would be different, but the output for them is the same – both print `{"pirateEnabled":true}`.

Can you please enlighten me if this is a bug or I misunderstood some assumption.

```typescript
export default function main() {
  let actor = new Actor();

  return [
    actor.greet(),
    actor, // first
    actor.enablePirate(),
    actor, // second
    actor.greet(),
  ];
}

class Actor {
  pirateEnabled = false;

  greet() {
    if (!this.pirateEnabled) {
      return "Hi";
    }

    return "Ahoy";
  }

  enablePirate() {
    this.pirateEnabled = true;
    return "Done";
  }
}
```

**Comment by voltrevo** [comment] 2023-03-07 00:54
Hi @mlajtos. This is a bug! Thanks for reporting it 😀.

The problem is that when the identifier `actor` is compiled it just emits the register `%actor` with no instructions needed. This is accurate at the position of evaluation, but in your example the register has changed by the time it is inserted:

```
mov [%_tmp0, %actor, %_tmp1, %actor, %_tmp2] %return
```

The simplest fix would be to always emit a `mov` instruction when compiling identifiers:

```
mov %actor %actor_here
mov %actor %actor_there
...
mov [%_tmp0, %actor_here, %_tmp1, %actor_there, %_tmp2] %return
```

But in most cases that would be excessive:

```ts
const y = x + x;
```

would be:

```
mov %x %_tmp0
mov %x %_tmp1
op+ %_tmp0 %_tmp1 %y
```

instead of just:

```
op+ %x %x %y
```

So I'm reluctant to apply the simple fix.

It will definitely be fixed one way or another though.

**Comment by voltrevo** [comment] 2023-03-07 01:12
As a demonstration, if you build the rust project, you can use `vstc` to run the assembly:

```
➜  ValueScript git:(main) ✗ vstc run --assembly actor.vsm         
[ "Hi", { pirateEnabled: true }, "Done", { pirateEnabled: true }, "Ahoy" ]
➜  ValueScript git:(main) ✗ vstc run --assembly actorCorrected.vsm
[ "Hi", { pirateEnabled: false }, "Done", { pirateEnabled: true }, "Ahoy" ]
```
```diff
--- actor.vsm   2023-03-07 12:09:38.000000000 +1100
+++ actorCorrected.vsm  2023-03-07 12:09:03.000000000 +1100
@@ -3,9 +3,11 @@
 @main = function() {
   new @Actor [] %actor
   subcall %actor "greet" [] %_tmp0
+  mov %actor %actor_here
   subcall %actor "enablePirate" [] %_tmp1
+  mov %actor %actor_there
   subcall %actor "greet" [] %_tmp2
-  mov [%_tmp0, %actor, %_tmp1, %actor, %_tmp2] %return
+  mov [%_tmp0, %actor_here, %_tmp1, %actor_there, %_tmp2] %return
 }
 
 @Actor_greet = function() {
```

(~The playground is slightly out of date right now, and needs `export @main {}` to be added at the top before passing it to the latest `vstc`.~ Playground updated. Future mismatches are expected though so ymmv if using the playground's assembly with your local `vstc`.)

**Comment by voltrevo** [comment] 2023-04-01 06:40
Fixed. We now allocate and move into a register for variables that have mutations. The number of unnecessary registers from this method isn't too bad, and can be tightened up in future, but might wait for an optimization pass rather than trying to suppress them in the first pass.

<img width="781" alt="Screen Shot 2023-04-01 at 5 37 13 pm" src="https://user-images.githubusercontent.com/9291586/229270023-036d276d-9aac-473b-92bc-debde8cd521d.png">

**Closed as completed by voltrevo** 2023-04-01 06:40 UTC
Labels: bug
